# Dev Profile with H2 Database
server.port=8080
spring.application.name=dosje-monitoring-backend

spring.datasource.url=jdbc:h2:mem:dosje_monitoring;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.sql.init.mode=never
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.jwt.secret=9a6747f3a1824d55b0a793a388b1480f2d1e2e9b08e5c14f7b6d92a08412e605
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=*
